// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Shared.Spy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.Spy;

[GenerateTypedNameReferences]
public sealed partial class SpyUplinkMenu : DefaultWindow
{
    public event Action<NetEntity>? OnClaim;

    public SpyUplinkMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(SpyUplinkBuiState state)
    {
        BountyList.RemoveAllChildren();

        foreach (var bounty in state.Bounties)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 4),
            };

            var info = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            var title = new Label
            {
                Text = bounty.Title,
                FontColorOverride = new Color(0.83f, 0.89f, 1f),
            };
            info.AddChild(title);

            if (!string.IsNullOrEmpty(bounty.Description))
            {
                var description = new RichTextLabel
                {
                    HorizontalExpand = true,
                };
                description.SetMessage(FormattedMessage.FromUnformatted(bounty.Description));
                info.AddChild(description);
            }

            string statusText;
            var statusColor = new Color(0.7f, 0.7f, 0.7f);
            if (bounty.Claimed)
            {
                statusText = Loc.GetString("spy-uplink-bounty-claimed");
                statusColor = new Color(0.55f, 0.75f, 0.55f);
            }
            else if (bounty.Completed)
            {
                statusText = Loc.GetString("spy-uplink-bounty-done");
                statusColor = new Color(0.6f, 0.9f, 0.6f);
            }
            else
            {
                statusText = Loc.GetString("spy-uplink-bounty-progress", ("progress", (int) (bounty.Progress * 100f)));
            }

            info.AddChild(new Label
            {
                Text = statusText,
                FontColorOverride = statusColor,
            });

            row.AddChild(info);

            var objective = bounty.Objective;
            var claim = new Button
            {
                Text = Loc.GetString("spy-uplink-claim"),
                Disabled = bounty.Claimed || !bounty.Completed,
                VerticalAlignment = VAlignment.Center,
                MinSize = new Vector2(90, 0),
            };
            claim.OnPressed += _ => OnClaim?.Invoke(objective);

            row.AddChild(claim);
            BountyList.AddChild(row);
        }
    }
}